cookies:
  filepath: cookies.json

websites:
  default:
    download-directory: "~/Downloads"
    login_func: login

  example:
    url: https://canvas.example.edu/
    landing_url: https://example.instructure.com/
    login_func: login_custom
